# Generated by Django 4.2.2 on 2023-06-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('resume', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('applied_date', models.DateField()),
                ('interview_date', models.DateField()),
                ('posted_date', models.DateField()),
            ],
        ),
    ]
